version: '3'

services:
  redis:
    image: redis
    ports:
    - 6379:6379

  app:
    build: .
    ports:
    - "3000"
    environment:
      REDIS_HOST: redis
    deploy:
      replicas: 3
    depends_on:
    - redis

  lb:
    image: nginx:latest
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
    - app
    ports:
    - "3000:3000"